dynamic: dynamic.c
	gcc -g -o dynamic dynamic.c

dynamic_recursive: dynamic_recursive.c
	gcc -g -o dynamic_recursive dynamic_recursive.c

efficient: efficient_iterative.c
	gcc -g -o efficient efficient_iterative.c

dynamic_iterative: dynamic_iterative.c
	gcc -g -o dynamic_iterative dynamic_iterative.c
